2019-12-08 20:37:00,595 [_worker] main loop worker ignores exception and continues: 'DateTime_Measured'
